# See https://gist.github.com/Robbepop/f88d896f859712384039813fab939172

# [rustfmt::skip]

max_width = 120
impl_empty_single_line = false
fn_empty_single_line = false
reorder_imports = true
wrap_comments = true
use_small_heuristics = "Max"