[package]
name = "rmule"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
pico-args = "0.5"
dirs = "4.0"
single-instance = "0.3"
rusqlite = { version = "0.28.0", features = ["bundled"] }

#case_insensitive_hashmap = "1.0"
#serde = { version = "1.0", features = ["derive"] }
#time = { version = "0.3", features = [ ] }
#toml = "0.5"
