[package]
name = "rmule"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
case_insensitive_hashmap = "1.0.0"
dirs = "4.0.0"
pico-args = "0.5.0"
time = { version = "0.3.17", features = [ ] }
