[workspace]
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0"
tokio = { version = "1.22", features = ["full", "tracing" ] }
tracing = "0.1.37"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

