[package]
name = "rmule"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
case_insensitive_hashmap = "1.0"
dirs = "4.0"
pico-args = "0.5"
serde = { version = "1.0", features = ["derive"] }
single-instance = "0.3"
time = { version = "0.3", features = [ ] }
toml = "0.5"
