[package]
name = "rmulegui"
version = "0.1.0"
edition = "2021"

[dependencies]
rmule = { path = "../rmule" }
pico-args = "0.5"
single-instance = "0.3"
anyhow = "1.0"
tokio = { version = "1.22", features = ["full", "tracing" ] }
tracing = "0.1.37"