[package]
name = "rmulegui"
version = "0.1.0"
edition = "2021"

[dependencies]
rmule = { path = "../rmule" }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
pico-args = "0.5"
single-instance = "0.3"
eframe = "0.20"
egui_extras = "0.20"
